export const INIT_TRUCKINGCOMPANIES = 'INIT_TRUCKINGCOMPANIES';
export const INIT_OPERATION = 'INIT_OPERATION';
export const UPDATE_OPERATION = 'UPDATE_OPERATION';
export const RESET_OPERATION = 'RESET_OPERATION';
export const CANCEL_OPERATION = 'CANCEL_OPERATION';
export const SELECT_NAVIGATION_TAB = 'SELECT_NAVIGATION_TAB';


