export const Role = {
  SYSTEM_ADMIN : 'SYSTEM_ADMIN',
  ADMIN : 'ADMIN',
  DISPATCHER : 'DISPATCHER',
  MANAGER : 'MANAGER',
  DRIVER : 'DRIVER',
  COMPANY_OWNER : 'COMPANY_OWNER',
  UNKNOWN_USER : ''
};
